### ISSUE TITLE
Criar conta no Glo

### ISSUE THREAD

**Issue by leonardo-minora** [q-box/q-box.github.io#14]
- [x] Acessar https://app.gitkraken.com/ e criar conta fazendo login pelo GitHub
ou
- [x] Baixar [VS Code](https://code.visualstudio.com) e instalar plugin Glo

- [x] Aceitar projeto QBox compartilhado por @leonardo-minora

**Comment by victordaniel102** [comment]
Esperando Mateus e Luciano concluírem para fechar a issue

**Comment by LuSizilio** [comment]
fiz pelo gitkraken falta @MatSilvaC  agora

**Comment by MatSilvaC** [comment]
pode fechar a issue @victordaniel102
