### ISSUE TITLE
Parte 2 - Boas práticas, Pág. 102 a 147, Introdução e boas práticas em UX Design

### ISSUE THREAD

**Issue by leonardo-minora** [q-box/q-box.github.io#4]
Parte 2 - Boas práticas, Pág. 102 a 147, Introdução e boas práticas em UX Design

Tarefas:
- [x] Criar slide slide-ux-02.pptx
- [x] Publicar slide slide-ux-02.pptx

**Comment by victordaniel102** [comment]
[Slide UX Design - Cap02](https://github.com/q-box/q-box.github.io/blob/master/ux/Slide%20UX%20Design%20-%20Cap02.odp)
