### ISSUE TITLE
Cap 2, Fundamentos sobre frameworks e ferramentas, Pág. 33 a 72

### ISSUE THREAD

**Issue by leonardo-minora** [q-box/q-box.github.io#5]
Cap 2, Fundamentos sobre frameworks e ferramentas, Pág. 33 a 72, Progressive Web Apps - Construa aplicações progressivas com react

Tarefas:
- [x] Criar slide slide-pwa-react-02.pptx
- [ ] Criar slide slide-pwa-react-03.pptx

**Comment by victordaniel102** [comment]
[ReactCap2](https://github.com/q-box/q-box.github.io/blob/master/pwa/ReactCap2.odp)

**Comment by leonardo-minora** [comment]
Atenção no nome dos arquivos ;-)

slide-pwa-react-02.pptx e não ReactCap2.odp

**Comment by victordaniel102** [comment]
Como essa issue se refere a semana passada, e a criação do capítulo 3 já está separada em outra issue, essa será fechada.
